# Generated by Django 6.0.7 on 2026-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_email_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('not_contacted', 'Not Contacted'), ('contacted', 'Contacted'), ('responded', 'Responded'), ('done', 'Done')], default='not_contacted', max_length=20),
        ),
    ]
